# Student_Performance Dataset

### Load and preprocess the Student_Performance.csv dataset.
### Build and train a Linear Regression model to predict the target variable.

## Requirements:
- Load the dataset.
- Perform required preprocessing.
- Handle categorical data where required.
- Split the data into training and testing sets.
- Train a Linear Regression model.
- Evaluate the model using:
- Mean Absolute Error (MAE)
- R² Score
- Create a Predictive Function that takes new input values and returns the prediction.
- Test the predictive function with at least one new input.
- Submit your complete Python file/notebook on the portal.

In [1]:
import pandas as pd
data = pd.read_csv("Student_Performance.csv")

In [2]:
data.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,Yes,5,2,36
4,7,75,No,8,5,66

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  int64
dtypes: int64(5), object(1)
memory usage: 468.9+ KB

In [4]:
data.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [5]:
data.duplicated().sum()

np.int64(127)

In [6]:
data.shape

(10000, 6)

In [7]:
data = data.drop_duplicates()

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [16]:
data.columns = [
    'Hours_Studied', 'Previous_Scores', 'Extracurricular_Activities',
       'SleepHours', 'Question_Papers_Practiced', 'Performance_Index'
]

In [20]:
data.head()

,Hours_Studied,Previous_Scores,Extracurricular_Activities,SleepHours,Question_Papers_Practiced,Performance_Index
0,7,99,1,9,1,91
1,4,82,0,4,2,65
2,8,51,1,7,2,45
3,5,52,1,5,2,36
4,7,75,0,8,5,66

In [18]:
data.Extracurricular_Activities.unique()

array(['Yes', 'No'], dtype=object)

In [19]:
data.Extracurricular_Activities = data.Extracurricular_Activities.map({
    "Yes" : 1,
    "No" : 0
})

In [27]:
X = data.drop("Performance_Index",axis=1)
y = data[["Performance_Index"]]

In [28]:
X.head()

,Hours_Studied,Previous_Scores,Extracurricular_Activities,SleepHours,Question_Papers_Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5

In [29]:
y.head()

   Performance_Index
0                 91
1                 65
2                 45
3                 36
4                 66

In [31]:
from sklearn.model_selection import train_test_split

In [33]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=35
)

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
student_model = LinearRegression()

In [36]:
student_model.fit(X_train, y_train)

LinearRegression()

In [37]:
y_pred = student_model.predict(X_test)

In [38]:
from sklearn.metrics import mean_absolute_error, r2_score

In [40]:
mean_absolute_error(y_test, y_pred)

1.6235384260319705

In [44]:
r2_score(y_test,y_pred)

0.9884248204916347

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9873 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               9873 non-null   int64
 1   Previous_Scores             9873 non-null   int64
 2   Extracurricular_Activities  9873 non-null   int64
 3   SleepHours                  9873 non-null   int64
 4   Question_Papers_Practiced   9873 non-null   int64
 5   Performance_Index           9873 non-null   int64
dtypes: int64(6)
memory usage: 798.0 KB

In [55]:
def student_model_predict():
    hours_study = int(input("Enter a Hours Study:"))
    previous_scroe = int(input("Enter a your previous score:"))
    activiites = int(input("Enter a Extra Circular Activites:"))
    sleep_hours = int(input("Enter a your sleep hours:"))
    question_paper = int(input("Enter a your question paper practiced:"))

    new_data = pd.DataFrame({
        "Hours_Studied" : [hours_study],
        "Previous_Scores" : [previous_scroe],
        "Extracurricular_Activities" : [activiites],
        "SleepHours": [sleep_hours],
        "Question_Papers_Practiced" : [question_paper]
    })

    prediction = student_model.predict(new_data)

    print(prediction[0])

In [58]:
student_model_predict()

Enter a Hours Study: 4
Enter a your previous score: 120
Enter a Extra Circular Activites: 4
Enter a your sleep hours: 7
Enter a your question paper practiced: 120

[128.6288704]