#  Ice Cream Sales & Temperature
```
Load and preprocess the dataset, build an ML Pipeline, and decide whether Linear Regression or Polynomial Regression performs better. Evaluate the model using MAE and R² Score and create a predictive function for new inputs.
```

In [16]:
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, r2_score

In [2]:
df = pd.read_csv("Ice Cream Sales and Temperature.csv")

In [3]:
df.head()

         Date   Time  Temperature (Celsius)  Ice Cream Sales
0  2023-01-01  08:00                     18               20
1  2023-01-01  08:05                     19               22
2  2023-01-01  08:10                     20               25
3  2023-01-01  08:15                     21               24
4  2023-01-01  08:20                     22               26

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   45 non-null     object
 1   Time                   45 non-null     object
 2   Temperature (Celsius)  45 non-null     int64
 3   Ice Cream Sales        45 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.5+ KB

In [5]:
df.isnull().sum()

Date                     0
Time                     0
Temperature (Celsius)    0
Ice Cream Sales          0
dtype: int64

In [7]:
df.columns

Index(['Date', 'Time', 'Temperature (Celsius)', 'Ice Cream Sales'], dtype='object')

In [8]:
df.columns = ([
    "Date", "Time", "Temperature", "Icecream_sales"
])

In [9]:
df.describe()

       Temperature  Icecream_sales
count    45.000000       45.000000
mean     40.000000       19.511111
std      13.133926       10.552083
min      18.000000        0.000000
25%      29.000000       11.000000
50%      40.000000       21.000000
75%      51.000000       28.000000
max      62.000000       38.000000

In [10]:
X = df[["Temperature"]]
y = df[["Icecream_sales"]]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
number_pipline = Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [17]:
preprocessor = ColumnTransformer([
    ("num",number_pipline,["Temperature"])
])

In [19]:
linear_pipline = Pipeline([
     ("preprocessing", preprocessor),
    ("model", LinearRegression())
])

In [20]:
linear_pipline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Temperature'])])),
                ('model', LinearRegression())])

In [22]:
y_pred = linear_pipline.predict(X_test)

# Model Evalution

In [24]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [25]:
mae

3.695402025763076

In [26]:
r2

0.8820257749190594

In [29]:
def predict_ice_cream_sales():
    temperature = float(input("Enter Temperature (Celsius): "))

    new_data = pd.DataFrame({
        "Temperature": [temperature]
    })

    prediction = linear_pipline.predict(new_data)

    print("Predicted Ice Cream Sales:", prediction[0])

In [30]:
predict_ice_cream_sales()

Enter Temperature (Celsius):  45

Predicted Ice Cream Sales: [16.26462998]