# Make a Housing Prices Machine Learning Pipline
```
Load and preprocess the dataset, build an ML Pipeline, and decide whether Linear Regression or Polynomial Regression performs better. Evaluate the model using MAE and R² Score and create a predictive function for new inputs.
```

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [6]:
df = pd.read_csv("Housing.csv")

In [7]:
df.head()

      price  area  bedrooms  bathrooms  stories  ... hotwaterheating airconditioning parking prefarea furnishingstatus
0  13300000  7420         4          2        3  ...              no             yes       2      yes        furnished
1  12250000  8960         4          4        4  ...              no             yes       3       no        furnished
2  12250000  9960         3          2        2  ...              no              no       2      yes   semi-furnished
3  12215000  7500         4          2        2  ...              no             yes       3      yes        furnished
4  11410000  7420         4          1        2  ...              no             yes       2       no        furnished

[5 rows x 13 columns]

In [8]:
df.describe()

              price          area    bedrooms   bathrooms     stories     parking
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505    0.693578
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492    0.861586
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000    0.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000    0.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000    0.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000    1.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000    3.000000