In [1]:
import pandas as pd
df = pd.read_csv("/content/Real estate.csv")

In [3]:
df

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
409,410,2013.000,13.7,4082.01500,0,24.94155,121.50381,15.4
410,411,2012.667,5.6,90.45606,9,24.97433,121.54310,50.0
411,412,2013.250,18.8,390.96960,7,24.97923,121.53986,40.6
412,413,2013.000,8.1,104.81010,5,24.96674,121.54067,52.5
413,414,2013.500,6.5,90.45606,9,24.97433,121.54310,63.9

In [9]:
df.drop(["No","X1 transaction date"],axis=1,inplace=True)

In [21]:
df.columns = ["age","Near_Station","number_of_stores","lat","long","price"]

In [22]:
df

      age  Near_Station  number_of_stores       lat       long  price
0    32.0      84.87882                10  24.98298  121.54024   37.9
1    19.5     306.59470                 9  24.98034  121.53951   42.2
2    13.3     561.98450                 5  24.98746  121.54391   47.3
3    13.3     561.98450                 5  24.98746  121.54391   54.8
4     5.0     390.56840                 5  24.97937  121.54245   43.1
..    ...           ...               ...       ...        ...    ...
409  13.7    4082.01500                 0  24.94155  121.50381   15.4
410   5.6      90.45606                 9  24.97433  121.54310   50.0
411  18.8     390.96960                 7  24.97923  121.53986   40.6
412   8.1     104.81010                 5  24.96674  121.54067   52.5
413   6.5      90.45606                 9  24.97433  121.54310   63.9

[414 rows x 6 columns]

In [23]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               414 non-null    float64
 1   Near_Station      414 non-null    float64
 2   number_of_stores  414 non-null    int64
 3   lat               414 non-null    float64
 4   long              414 non-null    float64
 5   price             414 non-null    float64
dtypes: float64(5), int64(1)
memory usage: 19.5 KB

In [25]:
# Features & Target
X = df.drop("price", axis=1)
y = df["price"]

In [27]:
num_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),   # handle missing numbers
    ("scaler", StandardScaler())
])

# Categorical pipeline
cat_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),  # handle missing categories
    ("encoder", OneHotEncoder(handle_unknown="ignore",sparse_output=False))
])

In [29]:
t1 = ColumnTransformer([
                            ("num", num_pipeline, make_column_selector(dtype_include=np.number)),
                            ("cat", cat_pipeline, make_column_selector(dtype_include=object))
])

In [46]:
model_pipeline = Pipeline([
                            ("preprocessing", t1),
                            ("poly", PolynomialFeatures(degree=3, include_bias=False)),
                            ("model", LinearRegression())
])

In [47]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [48]:
model_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7db967aa1550>),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7db965fd7440>)])),
                ('poly', PolynomialFeatures(degree=3, include_bias=False)),
                ('model', LinearRegression())])

In [49]:
y_pred_test = model_pipeline.predict(X_test)
r2 = r2_score(y_test, y_pred_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_test))

print("R2 Score:", r2)
print("RMSE:", rmse)

R2 Score: 0.7552649678658516
RMSE: 6.407549177804243