# Real State Data

#### Load and preprocess the Real estate.csv dataset.
#### Build and train a Linear Regression model to predict the target variable.

## Requirements:
- Load the dataset.
- Perform required preprocessing.
- Select the appropriate features and target variable.
- Split the data into training and testing sets.
- Train a Linear Regression model.
- Evaluate the model using:
- Mean Absolute Error (MAE)
- R² Score
- Create a Predictive Function that takes new input values and returns the prediction.
- Test the predictive function with at least one new input.

In [1]:
import pandas as pd
data = pd.read_csv("Real estate.csv")

In [2]:
data.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [3]:
data.shape

(414, 8)

In [4]:
data.drop(columns=["No"],axis=1, inplace=True)

In [5]:
data.isnull().sum()

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   X1 transaction date                     414 non-null    float64
 1   X2 house age                            414 non-null    float64
 2   X3 distance to the nearest MRT station  414 non-null    float64
 3   X4 number of convenience stores         414 non-null    int64
 4   X5 latitude                             414 non-null    float64
 5   X6 longitude                            414 non-null    float64
 6   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(1)
memory usage: 22.8 KB

In [8]:
data.columns = [
    "transaction_date",
    "house_age",
    "distance_to_mrt",
    "convenience_stores",
    "latitude",
    "longitude",
    "house_price"
]

In [9]:
data.head()

,transaction_date,house_age,distance_to_mrt,convenience_stores,latitude,longitude,house_price
0,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [14]:
X = data.drop(["house_price"], axis=1)
y = data[["house_price"]]

In [ ]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size=0.2 , random_state=42)

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
real_state_model = LinearRegression()

In [19]:
real_state_model.fit(X_train,y_train)

LinearRegression()

In [24]:
y_pred = real_state_model.predict(X_test)

In [20]:
from sklearn.metrics import mean_squared_error,r2_score

In [25]:
mean_squared_error(y_test, y_pred)

53.50561912450505

In [27]:
r2_score(y_test, y_pred)

0.6810580555095769

In [36]:
# Predict

def real_estate_predict():

    transaction_date = float(input("Enter Transaction Date: "))
    house_age = float(input("Enter House Age: "))
    distance_to_mrt = float(input("Enter Distance to MRT: "))
    convenience_stores = int(input("Enter Number of Convenience Stores: "))
    latitude = float(input("Enter Latitude: "))
    longitude = float(input("Enter Longitude: "))

    new_data = pd.DataFrame({
        "transaction_date": [transaction_date],
        "house_age": [house_age],
        "distance_to_mrt": [distance_to_mrt],
        "convenience_stores": [convenience_stores],
        "latitude": [latitude],
        "longitude": [longitude]
    })

    prediction = real_state_model.predict(new_data)

    print(prediction[0])

In [37]:
real_estate_predict()

Enter Transaction Date:  123
Enter House Age:  12
Enter Distance to MRT:  12
Enter Number of Convenience Stores:  12
Enter Latitude:  121
Enter Longitude:  1

[15319.48675378]